---
title: "insight-mixedmodels-test"
author: "Daniel Lüdecke"
date: "31 Januar 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(insight)
library(glmmTMB)

data(fish)
fish$ID = sample(1:4, nrow(fish), replace = TRUE)

m <- glmmTMB(
  count ~ child + camper + (1 | persons),
  ziformula = ~ child + livebait + (1 | ID),
  dispformula = ~ xb,
  data = fish,
  family = truncated_poisson()
)
```

## find_formula()

```{r}
find_formula(m)

find_formula(m, component = "cond")

find_formula(m, component = "zi")

find_formula(m, component = "disp")
```

## find_predictors()

```{r}
find_predictors(m)

find_predictors(m, effects = "random")

find_predictors(m, effects = "all")

find_predictors(m, component = "cond")

find_predictors(m, effects = "random", component = "cond")

find_predictors(m, effects = "all", component = "cond")

find_predictors(m, component = "zi")

find_predictors(m, effects = "random", component = "zi")

find_predictors(m, effects = "all", component = "zi")

find_predictors(m, component = "disp")

find_predictors(m, effects = "random", component = "disp")

find_predictors(m, effects = "all", component = "disp")
```

## find_random()

```{r}
find_random(m)

find_random(m, component = "cond")

find_random(m, component = "zi")

find_random(m, flatten = TRUE)

find_random(m, component = "cond", flatten = TRUE)

find_random(m, component = "zi", flatten = TRUE)
```

## find_response()

```{r}
find_response(m)
```

## find_terms()

```{r}
find_terms(m)

find_terms(m, flatten = TRUE)
```
