// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// has_single_value_.cpp
bool has_single_value_(std::vector<double> x, bool na_rm);
extern "C" SEXP _insight_has_single_value_(SEXP x, SEXP na_rm) {
  BEGIN_CPP11
    return cpp11::as_sexp(has_single_value_(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(na_rm)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_insight_has_single_value_", (DL_FUNC) &_insight_has_single_value_, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_insight(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
